### PR TITLE
docs(Javascript): Fix Table of Contents links

### PR DESCRIPTION
**Pull request by LucasC**
Some anchors in the table of contents were incorrect.

### CODE REVIEW

**Comment by vvo** [comment]
THX, do you know how to then generate the readme and push it to the js client?

**Comment by LucasC** [comment]
No, I don't. Do you mind handling that for me?

**Comment by vvo** [comment]
will do.

Otherwise, its easy:
- clone all api clients in your "Dev" directory so that you have:
  - dev/algoliasearch-client-js..
  - dev/algoliasearch-client..
  - dev/algoliasearch-client-readme-generator

Then inside dev/algoliasearch-client-readme-generator, you just do:

```sh
./doc-generator.rb ./config.json
```

You could also only clone the JS client and change the config.json just for the generation process.

This command will regenerate the readmes inside all the API clients, then you can open a PR with the changes

**Comment by vvo** [comment]
doing it now

**Pull request merged**
