### PR TITLE
Rewrote text about waitTask/taskID to make it (hopefully) clearer.

### PR DESCRIPTION
**Pull request by pixelastic**
I found the original sentence not clear enough (and a bit scary). Hope this is clearer.

cc @redox @Nagriar

### CODE REVIEW

**Comment by vvo** [comment]
I feel "Even if it's extremely fast, receiving a `taskID` does not mean
+that your task is already published to your index." is not very clear

**Comment by pixelastic** [comment]
I wanted to show that's it is async in nature, but still fast. Ideas on rephrasing it?

**Comment by vvo** [comment]
"All write operations are asynchronous. Write requests will be queued and you get a taskId when the request ends.

You can then use this waitTask(taskId) to know when your write task has completed."

?

**Comment by vvo** [comment]
Also see http://faq.algolia.com/troubleshooting/why-are-my-objects-not-immediately-available-for-search-after-adding-them/ where we already have some sort of explanation on this

**Comment by redox** [comment]
@pixelastic LGTM :+1:

**Comment by vvo** [comment]
> I wanted to show that's it is async in nature, but still fast. Ideas on rephrasing it?

We get that it is fast, but the "does not mean
+that your task is already published to your index" could be misinterpreted I guess.

**Pull request merged**
