### PR TITLE
Update Go snippets regarding the incoming V2 of the client

### PR DESCRIPTION
**Pull request by aseure**

### CODE REVIEW

**Comment by redox** [comment]
Looks good 👍

**Comment by redox** [comment]
Also, don't forget to add a message about migration like we do for Swift (see https://github.com/algolia/algoliasearch-client-readme-generator/tree/master/include/templates): 
```
<% if swift? -%> <Welcome Objective-C developers>

In July 2015, we released a new version of our Swift client, able to work with Swift and Objective-C. As of version 3 (April 2016), Swift has become the reference implementation for both Swift and Objective-C projects.

If you were using our Objective-C client, read the migration guide from Objective-C. The Objective-C API Client is no longer under active development. It is still supported for bug fixes, but will not receive new features.

</Welcome Objective-C developers><% end -%> 
```

**Comment by aseure** [comment]
@ercolanelli-leo If it's OK for you, you can just delete the `do not merge` label and ping @CBaptiste to know if it's possible to merge it.

**Comment by CBaptiste** [comment]
Just add "ready  to merge" and I ll merge it !

**Pull request merged**
