### PR TITLE
Fix links in js navigation

### PR DESCRIPTION
**Pull request by rayrutjes**
- Also removed the Parse.com reference

Resolves: #106

### CODE REVIEW

**Comment by redox** [comment]
Hmmm, I think we lost the parse.com paragraph then; because we have a dedicated build for parse.

**Comment by rayrutjes** [comment]
Ok, I removed the ready to merge label, let's figure out what happened to that paragraph first.

**Comment by rayrutjes** [comment]
@maxiloc this one needed some more work, that is why the label 'ready to merge' was not there anymore.

**Comment by maxiloc** [comment]
ah, then the do not merge would be better 😉

**Comment by maxiloc** [comment]
I missed it

**Pull request merged**
