### PR TITLE
Update `tagFilters` documentation: negation by dash prefix

### PR DESCRIPTION
**Pull request by clement-leprovost**

### CODE REVIEW

**Comment by alexandremeunier** [comment]
Awesome @clement-leprovost-algolia !

My only concern is that we are exposing 3 different syntaxes for using tag filters

1. `tags=tag1,(tag2,tag3)` means *tag1 AND (tag2 OR tag3)*. 
1. `tagFilters: ["tag1",["tag2","tag3"]]` means *tag1 AND (tag2 OR tag3)*. 
1. `tagFilters=tag1,-tag2`.

It's not super consistent, which is not that big of a deal, however is the first one (`tags=`) even valid ?

**Comment by clement-leprovost-algolia** [comment]
@alexandremeunier Oops you're right. I think the `tags` query parameter is still supported, but long deprecated. We should always use `tagFilters`. -> I'll update that.

**Comment by CBaptiste** [comment]
hello @clement-leprovost , is this PR still up to date ? since https://github.com/algolia/algoliasearch-client-readme-generator/pull/38 was merged ?

**Comment by clement-leprovost** [comment]
@CBaptiste From my point of view, these are two separate things, so I would say yes, we still need this PR.

**Comment by clement-leprovost** [comment]
Let me elaborate: we decided to promote the unified `filters` in the examples, but it doesn't mean we should not properly document the `tagFilters` parameter, since it still exists and is still supported.

**Comment by CBaptiste** [comment]
Alright, thank you !

**Pull request merged**
